plugins {
    id 'java'
}

allprojects {
    group = 'com.slfftz'
    version = '1.0.0'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(21)
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 21
    }

    tasks.withType(Jar).configureEach {
        archiveBaseName = "${project.parent.name}-${project.name}"
    }
}
