plugins {
    id 'net.neoforged.moddev' version "${moddev_gradle_version}"
    id 'java'
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

dependencies {
    implementation project(':core')
}

neoForge {
    version = neoForgeVersion

    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', ''
        }
        server {
            server()
            programArgument '--nogui'
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
            modId             : mod_id,
            version           : mod_version,
            displayName       : mod_name,
            description       : mod_description,
            neoForgeVersion   : neoForgeVersion,
            minecraftVersion  : minecraftVersion
    ]
    inputs.properties replaceProperties

    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}
